language: node_js
node_js:
  - 6
before_install:
  - npm i -g npm
script:
  - npm run lint
  - npm run test
  - npm run cover
  - npm run cover:check
after_install:
  - npm run cover:report
branches:
  only:
    - master
